# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32abc5d26a2087a873bd502234e8365766f8c58a92db0365a42762c62dc39a63446c82fd8ba60dda59b9ec82227df000d1b72bdb7da4e86670bc7bc6212feb4

test:
  secret_key_base: c9dde5c5220ba08e8a76a0997acf8926076c6677fe611c5e3c5a9eacee5d012e0ae9cb6552c169b69018f6980fe7b7d7c9a526bd0ab5de29bdab888e057c6993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
