# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1eaaf95b04f6d2c2f0a57c36f5a35e14aad08c15fdf48b49f0110b55bf5db991a664a6dc08eef6e647aee8688ae7e48ee77e574a28f11155bae3a636ae2f7c0

test:
  secret_key_base: 3c37f84ce4fd509709eb474b8ab274f0a35bd745ce481db446448e16d13fd579f6d605b175575588d8812449870a5c404f30020c6b8740e3bda3ae26bbdb89f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
